### assumes ubuntu 20.04 image
---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install packages
  apt: 
      pkg: 
          - curl
          - build-essential
          - git
          - python3
          - python3-pip
          - python3-setuptools
          - python3-dev
          - cython
          - default-jre
          - gnuplot-x11
          - bioperl
          - libssl-dev
          - cmake
          - hdf5-tools
          - pkg-config
      state: latest
  become: true

- name: install conda and snakemake
  include_tasks: conda.yml

- name: install docker
  include_tasks: docker.yml

- name: install singularity
  include_tasks: singularity.yml

- name: install nextflow
  include_tasks: nextflow.yml
