---
- name: nextflow | check if nextflow is installed
  stat: path="/usr/local/bin/nextflow"
  register: nextflowinstalled

- name: nextflow | remove old version of nextflow
  file:
    path: "/usr/local/bin/nextflow"
    state: absent
  when: nextflowinstalled.stat.exists

- name: nextflow | install nextflow
  shell: "wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v{{ nextflow_version }}/nextflow-{{ nextflow_version }}-all | bash"

- name: nextflow | copy nextflow to bin and set permissions
  copy:
    src: nextflow
    dest: /usr/local/bin/nextflow
    mode: a+x

- name: nextflow | remove downloaded file
  file:
    path: nextflow
    state: absent
