---
- name: singularity | install software dependencies
  apt:
    state: latest
  with_items:
    - build-essential
    - libssl-dev
    - uuid-dev
    - libgpgme11-dev
    - squashfs-tools
    - libseccomp-dev
    - pkg-config
    
- name: singularity | grab installer for go
  get_url: url=https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz mode=0755 

- name: singularity | remove old versions of go and install
  shell: "rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz"

- name: singularity| check if go is in PATH
  shell: "grep go ~/.bashrc"
  register: goinpath
  ignore_errors: True

- name: singularity | add go to PATH
  lineinfile: path="~/.bashrc" line="export PATH=/usr/local/go/bin:$PATH"
  when: goinpath.stdout == ""

- name: singularity | install go dependencies
  command: go get -u -v github.com/golang/dep/cmd/dep
 
- name: singularity | check if singularity is installed
  stat: path="/usr/local/singularity"
  register: singularityinstalled

- name: singularity | remove singularity if already installed
  shell: "rm -rf /usr/local/singularity"
  when: singularityinstalled.stat.exists

- name: singularity | create directory for singularity
  file:
  path: "singularity/src/github.com/sylabs/"
  recurse: True

- name: singularity | clone the Singularity repository
  git:
    repo: https://github.com/sylabs/singularity.git
    version: v3.8.3
    dest: "singularity/src/github.com/sylabs/singularity"

- name: singularity | compile the Singularity binary | mconfig
  command: ./mconfig --prefix=/usr/local/singularity
  args:
    chdir: "singularity/src/github.com/sylabs/singularity"

- name: singularity | compile the Singularity binary | make
  make:
    chdir: "singularity/src/github.com/sylabs/singularity/builddir"

- name: singularity | compile the Singularity binary | make install
  make:
    target: install
    chdir: "singularity/src/github.com/sylabs/singularity/builddir"

- name: singularity | check if singularity is in PATH
  shell: "grep singularity ~/.bashrc"
  register: singularityinpath
  ignore_errors: True

- name: singularity | add singularity to PATH
  lineinfile: path="~/.bashrc" line="export PATH=/usr/local/singularity/bin:$PATH"
  when: singularityinpath.stdout == ""
