---
- name: singularity | install software dependencies
  apt:
    state: latest
    pkg:
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - libseccomp-dev
      - pkg-config
  become: true

- name: singularity | grab installer for go
  get_url:
   url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
   dest: "{{ home }}"
   mode: 0755 

- name: singularity | check if go is installed
  stat: path="/usr/local/go"
  register: goinstalled

- name: singularity | remove old versions of go 
  shell: "rm -rf /usr/local/go"
  when: goinstalled.stat.exists
  become: yes

- name: singularity | install go
  shell: "tar -C /usr/local -xzf {{ home }}/ubuntu/go{{ go_version }}.linux-amd64.tar.gz"
  become: yes

- name: singularity | check if go is in PATH
  shell: "grep go ~/.bashrc"
  register: goinpath
  ignore_errors: True

- name: singularity | add go to PATH
  lineinfile: path="~/.bashrc" line="export PATH=/usr/local/go/bin:$PATH"
  when: goinpath.stdout == ""

- name: singularity | check if singularity is installed
  stat: path="/usr/local/singularity"
  register: singularityinstalled

- name: singularity | remove singularity if already installed
  shell: "rm -rf /usr/local/singularity"
  when: singularityinstalled.stat.exists
  become: yes

- name: singularity | create directory for singularity
  file:
    path: "{{ home }}/singularity/src/github.com/sylabs/"
    state: directory
    recurse: yes

- name: singularity | clone the Singularity repository
  git:
    repo: https://github.com/sylabs/singularity.git
    version: "{{ singularity_version }}"
    dest: "{{ home }}/singularity/src/github.com/sylabs/singularity"

- name: singularity | compile the Singularity binary | mconfig
  shell: "export PATH=/usr/local/go/bin:$PATH; ./mconfig --prefix=/usr/local/singularity"
  args:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity"
  become: true

- name: singularity | compile the Singularity binary | make
  make:
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"
  become: yes

- name: singularity | compile the Singularity binary | make install
  make:
    target: install
    chdir: "{{ home }}/singularity/src/github.com/sylabs/singularity/builddir"
  become: yes

- name: singularity | check if singularity is in PATH
  shell: "grep singularity ~/.bashrc"
  register: singularityinpath
  ignore_errors: True

- name: singularity | add singularity to PATH
  lineinfile: path="~/.bashrc" line="export PATH=/usr/local/singularity/bin:$PATH"
  when: singularityinpath.stdout == ""

- name: singularity | remove singularity source code
  shell: "rm -rf {{ home }}/singularity"
  become: yes

- name: singularity | remove go tar
  shell: "rm -f {{ home }}/go{{ go_version }}.linux-amd64.tar.gz"
  become: yes
